# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Github
  # Architecture
  pod 'ReactorKit'
 
  # Rx
  pod 'RxTexture2', '~> 1.3.0'
  pod 'RxDataSources-Texture'
  
  # Network
  pod 'Alamofire', '~>5.4.1'
  pod 'Moya', '~>14.0'

  # Misc
  pod 'Swinject'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Then'

end
